### ISSUE TITLE
"Throw" function seems misnamed

### ISSUE THREAD

**Issue by deadalusai** [odytrice/Operation#2]
This is just a note on the API method "Throw", which is documented as:

> Unwraps the Operation if Successful and Throws an Exception if an Operation Fails

The function name "Throw" implies that the method always throws, or throws for a failed operation (It looks like this is how it used to work?). However the method also returns the value of the operation on success - not really what it says on the tin.

Why not rename the function to "Unwrap"? That's the word you're using in the documentation and it seems to fit the actual use-case somewhat better as well.

**Comment by odytrice** [comment]
I think you are right. Unwrap is clearer. The reason behind throw was that it voilates the monad pattern in the sense that once your value is "wrapped" in a monad you should not be able to get it back. So I wanted it to be clear to anyone reading the code that bad things could happen when you try it. Similar to calling result on a Task<T> but as time went on, I discovered that it was a useful mechanism for propagating errors.

Anyways, at this point, removing it would be a breaking change for people that depend on it, However I will add an Unwrap extension and update the docs.
Thanks for the feedback :smile:

**Comment by deadalusai** [comment]
:+1:
