### ISSUE TITLE
Operation<IEnumerable> returns IEnumerable

### ISSUE THREAD

**Issue by ebi-igweze** [odytrice/Operation#4]
While using query expression syntax and interacting with an Operation<IEnumerable<T>>, the result of the expression is an IEnumerable<U> instead of Operation<IEnumerable<U>> i.e.
```csharp
var stringOps = Operation.Create(() => new List<string> { "Some", "String" });
var result = 
      from strings in stringOps
      from strng in strings
      select strng +" "+ "Appended String";      
```
"result" is an IEnumerable<string> instead of Operation<IEnumerable<string>>

**Comment by odytrice** [comment]
Yeah I've noticed the bug as well.

The type combinations should actually be as follows

```csharp
IEnumerable + Operation = IEnumerable<Operation>
Operation + IEnumerable = Operation<IEnumerable>
```
