### ISSUE TITLE
Create should take a Delegate that Returns Operation

### ISSUE THREAD

**Issue by odytrice** [odytrice/Operation#9]
`Operation.Create` should take a Delegate that Returns Operation and Unwrap it Implicitly. Instead of Throwing it explicitly
```csharp
Operation.Create(() => {
    //Do Some Operations
    var doStuff = SomeOperation(param1, param2)
    return doStuff;
});
```

**Comment by d-dantte** [comment]
yup

**Comment by odytrice** [comment]
Making this change causes a compiler error because the compiler can't distinguish between `Operation.Create<T>(Func<T> func)` and `Operation.Create<T>(Func<Operation<T>> func)` The best solution is to give this overload a new name.

**Comment by odytrice** [comment]
I ended up calling it `CreateBind` because it was clashing with the `Bind` Extension Method
